development:
  adapter: postgresql
  encoding: utf8
  database: desafio_development
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: desafio_test
  username: postgres
  password: postgres
  host: localhost
